//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobiController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asdf1 {
            get {
                object obj = ResourceManager.GetObject("asdf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;black&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;RSA&quot; CONTENT=&quot;no-cache&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;Expires&quot; CONTENT=&quot;-1&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;black&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;RSA&quot; CONTENT=&quot;no-cache&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;Expires&quot; CONTENT=&quot;-1&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;http://localhost/m/jquery.mobile-1.3.2.min.css&quot; /&gt;
        ///    &lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ControllerPart1 {
            get {
                return ResourceManager.GetString("ControllerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;!-- Home --&gt;
        ///    &lt;div data-role=&quot;page&quot; id=&quot;page1&quot; data-theme=&quot;a&quot;&gt;
        ///        &lt;div data-theme=&quot;a&quot; data-role=&quot;header&quot; data-position=&quot;fixed&quot;&gt;
        ///            &lt;h5&gt;.
        /// </summary>
        internal static string ControllerPart2 {
            get {
                return ResourceManager.GetString("ControllerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        &lt;/h5&gt;
        ///        &lt;/div&gt;
        ///        &lt;div data-role=&quot;content&quot;&gt;.
        /// </summary>
        internal static string ControllerPart3 {
            get {
                return ResourceManager.GetString("ControllerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;&lt;title&gt;Remote Manage&lt;/title&gt;&lt;/head&gt;&lt;body bgcolor=IndianRed&gt;&lt;h1&gt;&lt;font color=black&gt;404 - The Content Requested Was Not Found&lt;/font&gt;&lt;/h1&gt;&lt;a href=/controllers&gt; Go Back &lt;/a&gt; &lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string html404 {
            get {
                return ResourceManager.GetString("html404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;&lt;title&gt;Remote Manage&lt;/title&gt;&lt;/head&gt;&lt;body bgcolor=IndianRed&gt;&lt;h1&gt;&lt;font color=black&gt;403 - Acess to the requested resource was forbidden.&lt;/font&gt;&lt;/h1&gt;&lt;a href=auth.htm&gt; Go Back &lt;/a&gt; &lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string htmlforbid {
            get {
                return ResourceManager.GetString("htmlforbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Important {
            get {
                object obj = ResourceManager.GetObject("Important", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mysecret {
            get {
                object obj = ResourceManager.GetObject("mysecret", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no&quot;&gt;
        ///  &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot;&gt;
        ///  &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;black&quot;&gt;
        ///  &lt;META HTTP-EQUIV=&quot;RSA&quot; CONTENT=&quot;no-cache&quot;&gt;
        ///  &lt;META HTTP-EQUIV=&quot;Expires&quot; CONTENT=&quot;-1&quot;&gt;
        ///  &lt;title&gt;&lt;/title&gt;
        ///  
        ///  
        ///  
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;/&quot;&gt;
        ///  
        ///  &lt;!-- jQuery and jQuery Mobile --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/m/jquery.mobile-1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string remotelist {
            get {
                return ResourceManager.GetString("remotelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot;&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;black&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;RSA&quot; CONTENT=&quot;no-cache&quot;&gt;
        ///    &lt;META HTTP-EQUIV=&quot;Expires&quot; CONTENT=&quot;-1&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/m/jquery.mobile-1.3.2.min.css&quot; /&gt;
        ///    &lt;scr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tmpToolhtml {
            get {
                return ResourceManager.GetString("tmpToolhtml", resourceCulture);
            }
        }
    }
}
